# Primary Supabase project configuration for CLI operations.
# See https://supabase.com/docs/guides/cli/config for full schema.

project_id = "wnohgxkujwnuoqtibsss"

[remotes.production]
project_id = "wnohgxkujwnuoqtibsss"

[functions.check-email-status]
# Email probe runs before users authenticate, so disable JWT enforcement on this function.
verify_jwt = false

[functions.cleanup-orphaned-user]
# Cleanup function is unauthenticated (uses verification codes for auth), disable JWT enforcement.
verify_jwt = false
