name: Type Drift Check

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'supabase/migrations/**'
      - 'src/shared/types/supabase.ts'
      - 'package.json'
  push:
    branches: [main, develop]
    paths:
      - 'supabase/migrations/**'
      - 'src/shared/types/supabase.ts'

jobs:
  check-type-drift:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Generate types from Supabase schema
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          # Generate types to a temporary file
          supabase gen types typescript --project-id wnohgxkujwnuoqtibsss > src/shared/types/supabase.generated.ts

      - name: Check for type drift
        run: |
          # Compare generated types with committed version
          if ! diff -q src/shared/types/supabase.ts src/shared/types/supabase.generated.ts > /dev/null 2>&1; then
            echo "❌ Type drift detected!"
            echo ""
            echo "The generated TypeScript types do not match the committed version."
            echo "This indicates that the database schema has changed but types were not regenerated."
            echo ""
            echo "To fix this, run the following command locally:"
            echo "  npm run generate:types"
            echo ""
            echo "Then commit the updated types:"
            echo "  git add src/shared/types/supabase.ts"
            echo "  git commit -m 'chore: regenerate Supabase types'"
            echo ""
            echo "Diff between committed and generated types:"
            echo "─────────────────────────────────────────────"
            diff src/shared/types/supabase.ts src/shared/types/supabase.generated.ts || true
            exit 1
          else
            echo "✅ Type check passed - no drift detected"
          fi

      - name: Verify types compile
        run: npm run typecheck

      - name: Cleanup
        if: always()
        run: rm -f src/shared/types/supabase.generated.ts
